114843.387929 uso - Monkey Barrel [0.0.11](/scripts/diff/114843/387929)
- Failure with style sheet parsing when JavaScript is disabled... reverting to detection method in [0.0.8](/topics/89961?page=1#posts-390418)

```
Mozilla/5.0 (X11; Linux x86_64; rv:7.0.1) Gecko/20100101 Firefox/7.0.1
[Greasemonkey HEAD](http://github.com/greasemonkey/greasemonkey/commit/7ed47f93310ab3903ebfc26e1a9723acb325345a)
Clean profile and Running
```

```
Error: uncaught exception: [
  Exception... "A parameter or an operation is not supported by the underlying object"
  code: "15"
  nsresult: "0x8053000f (NS_ERROR_DOM_INVALID_ACCESS_ERR)"
  location: "resource://greasemonkey/runScript.js Line: 957"
]
```

Isolated to this code document.styleSheets.item(sheet).cssRules[rule] where sheet = 0 and rule = 0.  I'm not quite sure if this is related to [greasemonkey#1384](http://github.com/greasemonkey/greasemonkey/issues/1384) or if it is entirely unrelated.  It would appear that cssText in any instance is unreliable at this time. Any assignment even for testing throws the Exception with JavaScript disabled.

[https://bugzilla.mozilla.org/buglist.cgi?quicksearch=cssText](https://bugzilla.mozilla.org/buglist.cgi?quicksearch=cssText)[https://bugzilla.mozilla.org/buglist.cgi?quicksearch=cssRules](https://bugzilla.mozilla.org/buglist.cgi?quicksearch=cssRules)[https://bugzilla.mozilla.org/show_bug.cgi?id=470321](https://bugzilla.mozilla.org/show_bug.cgi?id=470321) vaguely resembles this.

[https://bugzilla.mozilla.org/show_bug.cgi?id=625013](https://bugzilla.mozilla.org/show_bug.cgi?id=625013) is a likely candidate. DOMContentLoaded fired and was trapped so it technically should already be in the DOM. :\

Hmmm this would appear to be a cross-domain restriction (inclusive to @namespace btw) imposed on the Sandbox/XPCNativeWrapper (restricted (content) scope wouldn't be any better).

The following code snippet [submitted](http://stackoverflow.com/questions/3211536/accessing-cross-domain-stylesheet-with-cssrules) as "Hope this helps someone." appears to be public domain to access same-domain sheets:

```
function cssAttributeGet(selectorText,attribute) {
  var styleSheet, rules, i, ii;
  selectorText=selectorText.toLowerCase();
  if (!document.styleSheets) {
    return false;
  }
  for (i=0; i<document.styleSheets.length; i++) {
    try{
      styleSheet=document.styleSheets[i];
      rules = (styleSheet.cssRules ? styleSheet.cssRules : styleSheet.rules);
      for (ii=0; ii<rules.length; ii++) {
        if (
          rules[ii] && rules[ii].selectorText &&
          rules[ii].selectorText.toLowerCase()===selectorText &&
          rules[ii].style[attribute]
        ){
          return (rules[ii].style[attribute]);
        }
      }
    }
    catch(e){
      // Do nothing!
    };
  }
  return false;
}
```

Computed values don't appear to be in the near future with JavaScript disabled so will continue with Used values for now.

114843.387929

SHA1:ba1b2ef9d3d9407907fef50511097598bd668a67